services:
  api:
    build: .
    container_name: be-godplan-api    
    env_file:
      - .env.prod
    environment:
      - OFFICE_LATITUDE=-6.301286
      - OFFICE_LONGITUDE=106.650010
      - ATTENDANCE_RADIUS_METERS=100
      - ENABLE_LOCATION_CHECK=true
    ports:
      - "8080:8080"
    networks:
      - godplan-shared-network   
    volumes:
      - ./ca.pem:/app/ca.pem:ro
      - ./docs:/app/docs:ro
    restart: unless-stopped

networks:
  godplan-shared-network:
    external: true                
    name: godplan-shared-network